---
title: ""
---

TELE-SPEAK Nepal is a digital care platform that connects Nepali clients globally with trained clinicians, while continuously improving care through in-house research and a sustainable cross-subsidy model.
It is designed to improve access to **speech, language and hearing health, and overall communication support** across Nepal and the Nepali diaspora globally.
Many individuals and families in Nepal face barriers to accessing specialized speech, language and hearing services due to limited availability of professionals, geographic challenges, travel burden, and lack of awareness.
TELE-SPEAK Nepal aims to reduce these barriers through accessible telepractice-based support delivered remotely/online.

---

## OUR VISION

To ensure that individuals across the globe have access to quality speech, language and hearing health services, regardless of their location.

---


## WHO WE SERVE?

- Children with communication delays  
- Adults with communication and swallowing difficulties  
- Individuals with hearing $\&$ tinnitus concerns or decreased sound tolerance
- Caregivers and families  
- Schools and community organizations

---

## OUR APPROACH

- Evidence/[research](https://nccsnepal.org/research.html) based practice  
- Multilingual tele-consultation (in Nepali, English, and Hindi)
- Family-centered support  
- Functional and real-life communication focus 
- Awareness-raising through workshops, training, and community education
- Referral guidance when in-person care is needed  
