---
title: ""
---


TELE-SPEAK Nepal provides online support for **speech, language, cognition, hearing, and overall communication needs** for both children and adults.

---

## WHO WE TREAT?

<div class="card">

### Children (5–17 years)

Support for speech, language, hearing, cognition and overall communication development.

</div>

<div class="card">

### Adults (18+ years)

Support for speech, language, cognitive, hearing, and overall communication problems

</div>

---

## SPEECH SERVICES

<div class="card">

We provide support for:

- Misarticulation and speech sound disorders  
- Stuttering and fluency disorders  
- Voice disorders (hoarseness, voice strain, voice fatigue etc.)  
- Dysarthria (motor speech disorders)  
- Speech clarity concerns  



</div>

---

## LANGUAGE SERVICES

<div class="card">

We provide support for:

- Delayed language development ( i.e.children not speaking age appropriately)
- Receptive language difficulties (i.e.difficulties in understanding language)  
- Expressive language difficulties (i.e.speaking and forming sentences)  
- language and learning-related communication concerns  


</div>

---

## COGNITIVE & NEUROLOGICAL COMMUNICATION SERVICES

<div class="card">

We provide support for:

- Aphasia (language impairment after stroke or brain injury)  
- Cognitive (e.g.memory, attention) difficulties  
- Communication changes due to neurological conditions (e.g.stroke)  


</div>

---

## HEARING SERVICES

<div class="card">

We provide support for:

- Hearing screening guidance  
- Hearing loss counseling  
- Listening difficulties (e.g.auditory processing disorders) 
- Hearing loss prevention strategies  
- Communication strategies for hearing devices (e.g hearing aids)
- Care and maintenance of hearing aids and cochlear implant
- Referral guidance for diagnostic audiological evaluation  

</div>

---

## TINNITUS COUNSELING

<div class="card">

We provide support for:

- Tinnitus education and awareness  
- Counseling and reassurance  
- Coping strategies  
- Sound enrichment guidance  

</div>

---

## CAREGIVER & FAMILY SUPPORT

<div class="card">

We provide support for:

- Parent and caregiver coaching  and training
- Home-based communication strategies  
- Communication partner training  

</div>